services:
  # Nginx
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./ejercicios/:/var/www/
      - ./nginx.php-fpm.conf:/etc/nginx/nginx.conf:ro
    links:
      - php-fpm

  # Configuración de php
  php-fpm:
    container_name: php
    build: .
    volumes:
      - ./ejercicios:/var/www/html

  #MariaDB
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: proyectosPDOTM4
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
